#Theme theme: jekyll-theme-cayman

# Site title
title: CardTrick
description: CardTrick

#permalinks
permalink: pretty

# Handling Reading
safe: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

# Use this for production
sass:
    style: compressed
exclude: [ README.md, LICENSE]


# Collection Management
collections_dir: users
collections:
  user1:
    output: true
  pgqgcycj:
    output: true
  ajsnsjsk:
    output: true
